// layout.tsx is the root shell that wraps every page in the app.
// Next.js renders this once and swaps only the {children} slot when navigating.
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// next/font loads fonts at build time and injects them as CSS variables —
// no external font request at runtime.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Exporting `metadata` tells Next.js what to put in <head> (title, description, etc.)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The default export must be named RootLayout and must render <html> and <body>.
// `children` is whatever page or nested layout Next.js matched for the current URL.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
